dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - ./test.sh
deploy:
  - provider: script
    script: docker build -t hhstechgroup/haproxy:$TRAVIS_TAG .
    on:
      tags: true
  - provider: script
    script: docker build -t hhstechgroup/haproxy:latest .
    on:
      branch: master
